# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/BusyDebugging"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/399897142"

# [social.params]
# icon = "brand-bilibili"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
